version: "3"

services:
  monapp:
    image: pythondoc
    depends_on:
      - redis
    ports:
      - "9090:80"
    networks:
      - mynetwork
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    
